pipeline {
    agent any
    environment {
        TRAIN_PATH      = 'train/train.csv'
        TRAIN_PREP_PATH = 'train/train_prep.csv'
        TEST_PATH       = 'test/test.csv'
        TEST_PREP_PATH  = 'test/test_prep.csv'
        MODEL_PATH      = 'model/model.pkl'
        PROJECT_PATH    = './practical_task_2'
    }
    stages {
        stage('Setup Python Environment') {
            steps {
                sh '''
                python3 -m venv $PROJECT_PATH/.venv;
                . $PROJECT_PATH/.venv/bin/activate;
                pip install -r  $PROJECT_PATH/requirements.txt;
                '''
            }
        }
        stage('Lint with flake8') {
            steps {
                sh '''
                . $PROJECT_PATH/.venv/bin/activate;
                flake8 $PROJECT_PATH/scripts --count --select=E9,F63,F7,F82 --show-source --statistics;
                flake8 $PROJECT_PATH/scripts --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics)
                '''
            }
        }
        stage('Create Data') {
            steps {
                sh '''
                . $PROJECT_PATH/.venv/bin/activate;
                python3 $PROJECT_PATH/scripts/data_creation.py;
                '''
            }
        }
        stage('Preprocess Data') {
            steps {
                sh '''
                . $PROJECT_PATH/.venv/bin/activate;
                python3 $PROJECT_PATH/scripts/data_preprocessing.py;
                '''
            }
        }
        stage('Prepare Model') {
            steps {
                sh '''
                . $PROJECT_PATH/.venv/bin/activate;
                python3 $PROJECT_PATH/scripts/model_preparation.py;
                '''
            }
        }
        stage('Test Model') {
            steps {
                sh '''
                . $PROJECT_PATH/.venv/bin/activate;
                python3 $PROJECT_PATH/scripts/model_testing.py;
                '''
            }
        }
    }
}
